language: node_js
node_js:
- '5'
sudo: required
before_install:
- npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email: false
  slack:
    secure: wTzAGUNv61KodeUAFmmIecv9LjEfrmgScu1UToyORgZXUslSun6Y03Y6QxUVAnz9EL6yaEWrNV0j4Ak5I+XeaR72xjCDeSaqL7j/w8k+AiaVnHsWjvlbtvv8qZhuCoE3+usUuSavlyQm6z1HQ3qa2cGUbpQPfJUaKfvuS3kwiyyfUtszmaSexMs7rTbO//vp19DkPXlxvlwyHJJ1DSDXCXLricCUAOvy886sNDrmKrxQsuNOK8Zp0W8TExYL/W1LB/GoMYgBViat3DSpbZtfetP48OPvYXG7p7osWNRxA6u4l8CHTjTu9NW9P6fFsKjtlM0+/7gk2YpCha+A0OV3O2KUhS0Geu9Y9p2GGrQ3NkiWEqLUhyDr1am5Cy+La6PahS1A3jel96HxRsWn8MhzHm6IJ+btdlrAUKoUVDpvRrjfeyebsuzQ/mcrBp4a6WX/0zF/fLRz4pHlLam181Twjhtz5DYyOYKksNjJY34HfHF8eFk7rIW0NoWt6VeeBkpf5TMspkbNigCCVZzGwWmioaSk/6Z5pTrhqmIofWaKydH2WXL7UKJlBWAkxa2tWpoJjaHmVZfiYnrc+nzpEQnjf5AC325PYkzZJ5kyNC45CzYMdZt3ubt3mJuWNvP6oHifsgLus2N8D/yNhBxQqL5cDTsXF31d58HYHpeJTYWGb+Y=
after_success:
- sh ./scripts/publish-docs-and-examples.sh
- npm run coverage
env:
  matrix:
    secure: I3hjR+BBPHlGBnxPCu+ey/6PuPRVsbyTSUyi09DDDTIa0SWhubvZgac2UQW9IJHY5jz5EOXOmk2nf9khGlz0pJdFsr3wyHbpFoTYmW2ns2EpqtqHLiz+4sQP4PQ3XZ6WdtRt63RkLYCaFMq6QHtHtpQP4kanWSuhqV6tUgjho1mZjXOEyY2/YcfVpVd0pa6u+S5/0WJEba3l0zBYkzyTp2WtiAGte0fYvO/5Q/vlWBUkE+zIsROpFVCP8yv29jwolsoH0a/v/sEOWglwIOU5ntyInir31edVVwiG4hGT8LBYG0JZbJlJyJvudZ68I9pB5ThdFsUZKOHWADwIhzD1EFOPXR/bPDuoEC/F3mOYbDm03GADHianQrYbIaupl+i8MnCJXDZFshrbtekOwvz56tOp31IZePR6EFAJOiwTejFdel09C01bWY7Yq4y5udOcNcWj6yUCLxTUKOVFM/JuySfZavdz4NhscfyrGPpXbsGMq0sR17EjFRRPPNq5aZ2mnpMG4q59rkdKHBzO6WPLHplD3EVjiZA0N6MgXktKBrsBjRJ/FjVzEz263wV5J7iY2h1RcgXPrJRM9JfQTd9XRxw4RH6yA4Gi9AMv6pG7m4uaLzagdmuiAp7Q9sn4s+d7vM43p9FDOpWXO7U+UO49xZ8zantY6oYXnfzCpXZTsKY=
